name: CI/CD para EC2 pública

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        host: 
          - name: "EC2-AZ1A-PUBLIC"
            remote_host: 3.225.148.41

          - name: "EC2-AZ1B-PUBLIC"
            remote_host: 35.171.78.172

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependências e Fazer Build
        run: |
             npm install
             npm run build --if-present

      - name: Copiar arquivos e Deploy (Usando SSH com rsync)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ matrix.host.remote_host }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/frontend
          ARGS: "-rltgoDzvO --delete" 
          SOURCE: "dist/"

      - name: Iniciar aplicação
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ matrix.host.remote_host }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker compose up -d

      - name: Obter endereços IP públicos das instâncias EC2
        run: |
          echo "Deploy de ${{ matrix.host.name }} concluído!"
          echo "Acesso em: http://${{ matrix.host.remote_host }}:80"
